--[[ Delin OS 打包器。 运行: lua5.1 tools/bundle.lua [kernel|dlub] [out.lua]
     kernel: 打包 src/kernel 内核模块 -> 单文件内核 bundle。
     dlub:   打包 DLUB 引导装载器(独立于内核) -> 单文件引导 bundle。
     产物用 Lua 5.2+ _ENV 技巧(CC 5.2+), 每个模块包一个 require 到内部 __require shim。 ]]

local target = arg[1] or "kernel"
local outPath = arg[2] or (target == "kernel" and "dist/kernel.lua" or "dist/dlub.lua")

local function readAll(p)
    local f = assert(io.open(p, "rb"), "cannot open " .. p)
    local c = f:read("*a")
    f:close()
    return c
end

local function longBracket(s)
    for level = 0, 10 do
        local close = "]" .. string.rep("=", level) .. "]"
        if not s:find(close, 1, true) then
            return "[" .. string.rep("=", level) .. "[" .. s .. close
        end
    end
    error("cannot find free long-bracket level for asset")
end

-- 两个 profile 的模块与资产
local profiles = {
    kernel = {
        modules = {
            ["kernel.scheduler"] = "src/kernel/scheduler.lua",
            ["kernel.process"]   = "src/kernel/process.lua",
            ["kernel.signal"]    = "src/kernel/signal.lua",
            ["kernel.boot"]      = "src/kernel/boot.lua",
            ["kernel.vfs"]       = "src/kernel/vfs.lua",
            ["kernel.vfs_api"]   = "src/kernel/vfs_api.lua",
            ["kernel.modules"]   = "src/kernel/modules.lua",
            ["kernel.blockdev"]  = "src/kernel/blockdev.lua",
            ["kernel.ext2"]      = "src/kernel/ext2.lua",
            ["kernel.user"]      = "src/kernel/user.lua",
            ["kernel.display"]   = "src/kernel/display.lua",
            ["kernel.tty"]       = "src/kernel/tty.lua",
            ["kernel.fb"]        = "src/kernel/fb.lua",
            ["kernel.sysfs"]     = "src/kernel/sysfs.lua",
        },
        assets = {
            ["init"]      = "src/init/init.lua",
            ["ext2_init"] = "src/init/ext2_init.lua",
        },
        entry = "__require('kernel.boot').boot()",
    },
    dlub = {
        modules = {
            ["kernel.blockdev"] = "src/kernel/blockdev.lua",
            ["kernel.ext2"]     = "src/kernel/ext2.lua",
            ["kernel.manifest"] = "src/kernel/manifest.lua",
            ["kernel.dlub"]     = "src/kernel/dlub.lua",
        },
        assets = {},
        entry = "__require('kernel.dlub').master()",
    },
}

local profile = assert(profiles[target], "unknown target: " .. target)

local out = {}
out[#out + 1] = "-- Delin OS " .. target .. " bundle (generated by tools/bundle.lua) -- do not edit"
out[#out + 1] = "local __chunks = {}"
out[#out + 1] = "local __loaded = {}"
out[#out + 1] = "local function __require(name)"
out[#out + 1] = "    if __loaded[name] then return __loaded[name] end"
out[#out + 1] = "    local chunk = assert(__chunks[name], 'module not found: ' .. name)"
out[#out + 1] = "    local mod = chunk()"
out[#out + 1] = "    __loaded[name] = mod"
out[#out + 1] = "    return mod"
out[#out + 1] = "end"

for name, src in pairs(profile.modules) do
    local code = readAll(src)
    out[#out + 1] = string.format("__chunks[%q] = function()", name)
    out[#out + 1] = "    local _ENV = setmetatable({ require = __require }, { __index = _G })"
    out[#out + 1] = code
    out[#out + 1] = "end"
end

for name, src in pairs(profile.assets) do
    local code = readAll(src)
    out[#out + 1] = string.format("__chunks[%q] = function()", "kernel." .. name .. "_src")
    out[#out + 1] = "    return " .. longBracket(code)
    out[#out + 1] = "end"
end

out[#out + 1] = profile.entry

local body = table.concat(out, "\n")
local f = assert(io.open(outPath, "w"))
f:write(body)
f:close()
print("wrote " .. outPath .. " (" .. #body .. " bytes)")
