--[[ Delin OS bundle generator.
     Runs with lua5.1:  lua5.1 tools/bundle.lua [out.lua]
     Reads src/**/*.lua (modules) and src/init/init.lua (asset -> kernel.init_src),
     emits a single self-contained Lua file to out.lua (default dist/delin-0.0.1.lua).

     The emitted file uses the Lua 5.2+ `_ENV` trick (CC-Tweaked is 5.2+), so each
     bundled module gets `require` wired to the internal `__require` shim. ]]

local outPath = arg[1] or "dist/delin-0.0.1.lua"

local function readAll(p)
    local f = assert(io.open(p, "rb"), "cannot open " .. p)
    local c = f:read("*a")
    f:close()
    return c
end

-- module:  name -> 源文件路径
local modules = {
    ["kernel.scheduler"] = "src/kernel/scheduler.lua",
    ["kernel.process"]   = "src/kernel/process.lua",
    ["kernel.boot"]      = "src/kernel/boot.lua",
    ["kernel.vfs"]       = "src/kernel/vfs.lua",
    ["kernel.vfs_api"]   = "src/kernel/vfs_api.lua",
    ["kernel.modules"]   = "src/kernel/modules.lua",
    ["kernel.blockdev"]  = "src/kernel/blockdev.lua",
    ["kernel.ext2"]      = "src/kernel/ext2.lua",
    ["kernel.manifest"]  = "src/kernel/manifest.lua",
    ["kernel.dlub"]      = "src/kernel/dlub.lua",
}
-- asset(source 字符串) -> 源文件路径
local assets = {
    ["init"]        = "src/init/init.lua",
    ["ext2_init"]   = "src/init/ext2_init.lua",
}

-- 选一个 init 源码里不出现的长括号定界符层数。
local function longBracket(s)
    for level = 0, 10 do
        local close = "]" .. string.rep("=", level) .. "]"
        if not s:find(close, 1, true) then
            return "[" .. string.rep("=", level) .. "[" .. s .. close
        end
    end
    error("cannot find free long-bracket level for asset")
end

local out = {}
out[#out + 1] = "-- Delin OS 0.0.1 bundle (generated by tools/bundle.lua) -- do not edit"
out[#out + 1] = "local __chunks = {}"
out[#out + 1] = "local __loaded = {}"
out[#out + 1] = "local function __require(name)"
out[#out + 1] = "    if __loaded[name] then return __loaded[name] end"
out[#out + 1] = "    local chunk = assert(__chunks[name], 'module not found: ' .. name)"
out[#out + 1] = "    local mod = chunk()"
out[#out + 1] = "    __loaded[name] = mod"
out[#out + 1] = "    return mod"
out[#out + 1] = "end"

for name, src in pairs(modules) do
    local code = readAll(src)
    out[#out + 1] = string.format("__chunks[%q] = function()", name)
    out[#out + 1] = "    local _ENV = setmetatable({ require = __require }, { __index = _G })"
    out[#out + 1] = code
    out[#out + 1] = "end"
end

for name, src in pairs(assets) do
    local code = readAll(src)
    out[#out + 1] = string.format("__chunks[%q] = function()", "kernel." .. name .. "_src")
    out[#out + 1] = "    return " .. longBracket(code)
    out[#out + 1] = "end"
end

out[#out + 1] = "__require('kernel.boot').boot()"

local body = table.concat(out, "\n")
local f = assert(io.open(outPath, "w"))
f:write(body)
f:close()
print("wrote " .. outPath .. " (" .. #body .. " bytes)")
